#                      Scope: Part 1 of Compose.yml
#               Installation: Please use the all-in-one file Compose.yml, not this file.
#                       Date: See Compose.yml
#                    Version: See # # Output of keyboard layout version number
<UEFA0>                     : "version 6.2.6.0" # See #   End of line comments
#       Operating file name*: .XCompose or Compose
#                   Encoding: UTF-8
#                       Type: text/XCompose
#                Description: Multicharacter and multikey configuration
#                   Platform: Linux using XKB with XCompose**
#     Syntactic highlighting: YAML
#
@	* Simplifier les séquences de "⟊" U27CA, "⟎" U27CE, "⟏" U27CF, "⟦" U27E6, "⟧" U27E7.
#
#
#   See part 2 in compose-2.yml
#   See part 3 in compose-3.yml
#
